// <auto-generated />
using System;
using EAgendaMedica.Infra.Compartilhado;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EAgendaMedica.Infra.Migrations
{
    [DbContext(typeof(EAgendaMedicaDBContext))]
    [Migration("20231113005050_migration-medico")]
    partial class migrationmedico
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EAgendaMedica.Dominio.ModuloMedico.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CRM")
                        .IsUnique();

                    b.ToTable("TB_Medico", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c792efe-118d-448b-82f4-700cef800309"),
                            CRM = "12345-SC",
                            Nome = "Médico 1"
                        },
                        new
                        {
                            Id = new Guid("ba23668e-e59e-4ca0-8e7a-3ab654f48882"),
                            CRM = "67890-SC",
                            Nome = "Médico 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
