// <auto-generated />
using System;
using EAgendaMedica.Infra.Compartilhado;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EAgendaMedica.Infra.Migrations
{
    [DbContext(typeof(EAgendaMedicaDBContext))]
    partial class EAgendaMedicaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EAgendaMedica.Dominio.ModuloMedico.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CRM")
                        .IsUnique();

                    b.ToTable("TB_Medico", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("74d7d3e7-7227-41d2-bb69-f0f22b0d089f"),
                            CRM = "12345-SC",
                            Nome = "Médico 1"
                        },
                        new
                        {
                            Id = new Guid("9e4c827c-9279-4ea7-8fb7-3b911068273a"),
                            CRM = "67890-SC",
                            Nome = "Médico 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
